/**
 * Markdown Exporter Tests
 *
 * Issue #25: Session Recording & Export
 */

import { describe, it, expect } from 'vitest';
import { exportToMarkdown, getDefaultMarkdownFilename } from '../../../electron/session/exporters/markdown-exporter';
import type { SessionRecord } from '../../../electron/session/types';

describe('MarkdownExporter', () => {
  const mockSession: SessionRecord = {
    id: 'session-123456-abc123',
    debateId: 'debate-789',
    startedAt: '2025-12-30T10:00:00.000Z',
    endedAt: '2025-12-30T10:15:00.000Z',
    status: 'completed',
    config: {
      topic: 'Test Topic',
      context: 'Test Context',
      preset: 'code_review',
      participants: ['chatgpt', 'claude'],
      judgeProvider: 'gemini',
      completionThreshold: 90,
    },
    messages: [
      {
        id: 'msg-1',
        timestamp: '2025-12-30T10:00:05.000Z',
        provider: 'chatgpt',
        role: 'user',
        content: 'Test prompt',
        tokenCount: 5,
        iteration: 1,
      },
      {
        id: 'msg-2',
        timestamp: '2025-12-30T10:00:30.000Z',
        provider: 'chatgpt',
        role: 'assistant',
        content: 'Test response',
        tokenCount: 10,
        iteration: 1,
      },
    ],
    elements: [
      {
        id: 'elem-1',
        name: '보안',
        status: 'completed',
        currentScore: 95,
        scoreHistory: [80, 90, 95],
        versionHistory: [],
        completionReason: 'threshold',
      },
    ],
    metadata: {
      totalTokens: 15,
      totalIterations: 1,
      providersUsed: ['chatgpt', 'claude'],
      completionReason: 'consensus',
    },
  };

  describe('exportToMarkdown', () => {
    it('should export session as markdown with header', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('# MAD 토론 세션 기록');
      expect(markdown).toContain('**Session ID**: session-123456-abc123');
      expect(markdown).toContain('**Preset**: code_review');
    });

    it('should include topic and context', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('## 토론 주제');
      expect(markdown).toContain('Test Topic');
      expect(markdown).toContain('### 컨텍스트');
      expect(markdown).toContain('Test Context');
    });

    it('should include participants', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('## 참여자');
      expect(markdown).toContain('chatgpt, claude');
      expect(markdown).toContain('gemini');
    });

    it('should include messages grouped by iteration', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('## 대화 기록');
      expect(markdown).toContain('### Iteration 1');
      expect(markdown).toContain('Test prompt');
      expect(markdown).toContain('Test response');
    });

    it('should include provider emojis', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('💚'); // chatgpt
    });

    it('should include elements table', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('## 평가 요소');
      expect(markdown).toContain('| 요소 | 상태 | 점수 | 완료 사유 |');
      expect(markdown).toContain('보안');
      expect(markdown).toContain('95');
    });

    it('should include metadata by default', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('## 메타데이터');
      expect(markdown).toContain('**총 토큰**: 15');
      expect(markdown).toContain('**완료 사유**: 합의 도달');
    });

    it('should exclude metadata when option is false', () => {
      const markdown = exportToMarkdown(mockSession, { includeMetadata: false });

      expect(markdown).not.toContain('## 메타데이터');
      expect(markdown).not.toContain('**총 토큰**');
    });

    it('should include footer with generation info', () => {
      const markdown = exportToMarkdown(mockSession);

      expect(markdown).toContain('---');
      expect(markdown).toContain('Generated by MAD Framework');
    });

    it('should handle session without context', () => {
      const sessionNoContext = {
        ...mockSession,
        config: { ...mockSession.config, context: undefined },
      };

      const markdown = exportToMarkdown(sessionNoContext);

      expect(markdown).not.toContain('### 컨텍스트');
    });

    it('should handle session without elements', () => {
      const sessionNoElements = {
        ...mockSession,
        elements: [],
      };

      const markdown = exportToMarkdown(sessionNoElements);

      expect(markdown).not.toContain('## 평가 요소');
    });
  });

  describe('getDefaultMarkdownFilename', () => {
    it('should generate filename with date and session ID', () => {
      const filename = getDefaultMarkdownFilename(mockSession);

      expect(filename).toMatch(/^mad-session-\d{8}-\d{6}-[a-z0-9]+\.md$/);
      expect(filename).toContain('abc123');
    });
  });
});
