/**
 * Markdown Exporter
 *
 * Issue #25: 세션을 Markdown 형식으로 내보내기
 * P2: 부분 내보내기 지원
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SessionRecord, ExportOptions, PartialExportOptions, MessageRecord } from '../types';

/**
 * 세션을 Markdown 형식으로 내보내기
 */
export function exportToMarkdown(
  session: SessionRecord,
  options: ExportOptions = {}
): string {
  const { includeMetadata = true } = options;

  const lines: string[] = [];

  // 헤더
  lines.push('# MAD 토론 세션 기록');
  lines.push('');

  // 세션 정보
  lines.push(`**Session ID**: ${session.id}`);
  lines.push(`**Debate ID**: ${session.debateId}`);
  lines.push(`**Preset**: ${session.config.preset}`);
  lines.push(`**시작**: ${formatDateTime(session.startedAt)}`);
  if (session.endedAt) {
    lines.push(`**종료**: ${formatDateTime(session.endedAt)}`);
  }
  lines.push(`**상태**: ${translateStatus(session.status)}`);
  lines.push('');

  // 토론 주제
  lines.push('## 토론 주제');
  lines.push('');
  lines.push(session.config.topic);
  lines.push('');

  if (session.config.context) {
    lines.push('### 컨텍스트');
    lines.push('');
    lines.push(session.config.context);
    lines.push('');
  }

  // 참여자
  lines.push('## 참여자');
  lines.push('');
  lines.push(`- **토론자**: ${session.config.participants.join(', ')}`);
  lines.push(`- **심판**: ${session.config.judgeProvider}`);
  lines.push('');

  // 대화 기록
  lines.push('## 대화 기록');
  lines.push('');

  // 메시지를 iteration별로 그룹화
  const messagesByIteration = groupMessagesByIteration(session.messages);

  for (const [iteration, messages] of Object.entries(messagesByIteration)) {
    lines.push(`### Iteration ${iteration}`);
    lines.push('');

    for (const msg of messages) {
      const roleLabel = msg.role === 'user' ? '📝 User' : '🤖 Assistant';
      const time = formatTime(msg.timestamp);
      lines.push(`#### ${getProviderEmoji(msg.provider)} ${msg.provider} (${roleLabel}) - ${time}`);
      lines.push('');
      lines.push(msg.content);
      lines.push('');
    }
  }

  // 요소 결과 (있는 경우)
  if (session.elements.length > 0) {
    lines.push('## 평가 요소');
    lines.push('');
    lines.push('| 요소 | 상태 | 점수 | 완료 사유 |');
    lines.push('|------|------|------|----------|');

    for (const element of session.elements) {
      const statusEmoji = element.status === 'completed' ? '✅' :
                         element.status === 'cycle_detected' ? '🔄' : '⏳';
      const reason = element.completionReason === 'threshold' ? '임계값 도달' :
                    element.completionReason === 'cycle' ? '순환 감지' : '-';
      lines.push(`| ${element.name} | ${statusEmoji} ${element.status} | ${element.currentScore} | ${reason} |`);
    }
    lines.push('');
  }

  // 메타데이터 (옵션)
  if (includeMetadata) {
    lines.push('## 메타데이터');
    lines.push('');
    lines.push(`- **총 토큰**: ${session.metadata.totalTokens.toLocaleString()}`);
    lines.push(`- **총 반복**: ${session.metadata.totalIterations}회`);
    lines.push(`- **사용 Provider**: ${session.metadata.providersUsed.join(', ')}`);
    if (session.metadata.completionReason) {
      lines.push(`- **완료 사유**: ${translateCompletionReason(session.metadata.completionReason)}`);
    }
    lines.push('');
  }

  // 푸터
  lines.push('---');
  lines.push(`*Generated by MAD Framework at ${formatDateTime(new Date().toISOString())}*`);

  return lines.join('\n');
}

/**
 * 세션을 Markdown 파일로 저장
 */
export async function exportToMarkdownFile(
  session: SessionRecord,
  outputPath: string,
  options: ExportOptions = {}
): Promise<void> {
  const markdown = exportToMarkdown(session, options);

  // 디렉토리가 없으면 생성
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, markdown, 'utf-8');
  console.log(`[MarkdownExporter] Exported session to: ${outputPath}`);
}

/**
 * 기본 내보내기 파일명 생성
 */
export function getDefaultMarkdownFilename(session: SessionRecord): string {
  const date = new Date(session.startedAt);
  const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '');
  const timeStr = date.toISOString().slice(11, 19).replace(/:/g, '');
  return `mad-session-${dateStr}-${timeStr}-${session.id.slice(-6)}.md`;
}

// Helper functions

function formatDateTime(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleString('ko-KR', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

function formatTime(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleTimeString('ko-KR', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

function translateStatus(status: string): string {
  const statusMap: Record<string, string> = {
    active: '진행 중',
    completed: '완료',
    cancelled: '취소됨',
    error: '오류',
  };
  return statusMap[status] || status;
}

function translateCompletionReason(reason: string): string {
  const reasonMap: Record<string, string> = {
    consensus: '합의 도달',
    cycle: '순환 감지',
    maxIterations: '최대 반복 도달',
    cancelled: '사용자 취소',
    error: '오류 발생',
  };
  return reasonMap[reason] || reason;
}

function getProviderEmoji(provider: string): string {
  const emojiMap: Record<string, string> = {
    chatgpt: '💚',
    claude: '🟠',
    gemini: '🔵',
  };
  return emojiMap[provider] || '⚪';
}

function groupMessagesByIteration(
  messages: SessionRecord['messages']
): Record<number, SessionRecord['messages']> {
  const grouped: Record<number, SessionRecord['messages']> = {};

  for (const msg of messages) {
    if (!grouped[msg.iteration]) {
      grouped[msg.iteration] = [];
    }
    grouped[msg.iteration].push(msg);
  }

  return grouped;
}

/**
 * 메시지 필터링 헬퍼 (P2)
 */
function filterMessages(
  messages: MessageRecord[],
  options: PartialExportOptions
): MessageRecord[] {
  const { iterations, providers, roles, fromTime, toTime } = options;
  let filtered = messages;

  if (iterations && iterations.length > 0) {
    filtered = filtered.filter((msg) => iterations.includes(msg.iteration));
  }

  if (providers && providers.length > 0) {
    filtered = filtered.filter((msg) => providers.includes(msg.provider));
  }

  if (roles && roles.length > 0) {
    filtered = filtered.filter((msg) => roles.includes(msg.role));
  }

  if (fromTime) {
    const fromDate = new Date(fromTime).getTime();
    filtered = filtered.filter((msg) => new Date(msg.timestamp).getTime() >= fromDate);
  }

  if (toTime) {
    const toDate = new Date(toTime).getTime();
    filtered = filtered.filter((msg) => new Date(msg.timestamp).getTime() <= toDate);
  }

  return filtered;
}

/**
 * 부분 내보내기 (P2)
 */
export function exportToMarkdownPartial(
  session: SessionRecord,
  options: PartialExportOptions = {}
): string {
  const { includeMetadata = true } = options;

  // 메시지 필터링
  const filteredMessages = filterMessages(session.messages, options);

  const lines: string[] = [];

  // 헤더
  lines.push('# MAD 토론 세션 기록 (부분)');
  lines.push('');

  // 필터 정보
  lines.push('> 부분 내보내기');
  if (options.iterations) {
    lines.push(`> - Iterations: ${options.iterations.join(', ')}`);
  }
  if (options.providers) {
    lines.push(`> - Providers: ${options.providers.join(', ')}`);
  }
  if (options.roles) {
    lines.push(`> - Roles: ${options.roles.join(', ')}`);
  }
  lines.push('');

  // 세션 정보
  lines.push(`**Session ID**: ${session.id}`);
  lines.push(`**Debate ID**: ${session.debateId}`);
  lines.push(`**Preset**: ${session.config.preset}`);
  lines.push(`**시작**: ${formatDateTime(session.startedAt)}`);
  if (session.endedAt) {
    lines.push(`**종료**: ${formatDateTime(session.endedAt)}`);
  }
  lines.push(`**상태**: ${translateStatus(session.status)}`);
  lines.push('');

  // 토론 주제
  lines.push('## 토론 주제');
  lines.push('');
  lines.push(session.config.topic);
  lines.push('');

  // 대화 기록
  lines.push('## 대화 기록');
  lines.push('');

  const messagesByIteration = groupMessagesByIteration(filteredMessages);

  for (const [iteration, messages] of Object.entries(messagesByIteration)) {
    lines.push(`### Iteration ${iteration}`);
    lines.push('');

    for (const msg of messages) {
      const roleLabel = msg.role === 'user' ? '📝 User' : '🤖 Assistant';
      const time = formatTime(msg.timestamp);
      lines.push(`#### ${getProviderEmoji(msg.provider)} ${msg.provider} (${roleLabel}) - ${time}`);
      lines.push('');
      lines.push(msg.content);
      lines.push('');
    }
  }

  // 메타데이터 (필터링된 버전)
  if (includeMetadata) {
    const filteredMetadata = {
      totalTokens: filteredMessages.reduce((sum, msg) => sum + (msg.tokenCount || 0), 0),
      totalIterations: Math.max(0, ...filteredMessages.map((msg) => msg.iteration)),
      providersUsed: [...new Set(filteredMessages.map((msg) => msg.provider))],
    };

    lines.push('## 메타데이터 (필터링됨)');
    lines.push('');
    lines.push(`- **필터링된 메시지 수**: ${filteredMessages.length}개`);
    lines.push(`- **총 토큰**: ${filteredMetadata.totalTokens.toLocaleString()}`);
    lines.push(`- **총 반복**: ${filteredMetadata.totalIterations}회`);
    lines.push(`- **사용 Provider**: ${filteredMetadata.providersUsed.join(', ')}`);
    lines.push('');
  }

  // 푸터
  lines.push('---');
  lines.push(`*Generated by MAD Framework (Partial Export) at ${formatDateTime(new Date().toISOString())}*`);

  return lines.join('\n');
}

/**
 * 부분 내보내기를 파일로 저장 (P2)
 */
export async function exportToMarkdownFilePartial(
  session: SessionRecord,
  outputPath: string,
  options: PartialExportOptions = {}
): Promise<void> {
  const markdown = exportToMarkdownPartial(session, options);

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, markdown, 'utf-8');
  console.log(`[MarkdownExporter] Exported partial session to: ${outputPath}`);
}
